LabForWeb.MVC/Controllers/CarrelloController.cs
using LabForWeb.MVC.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using LabForWeb.MVC.Data.Models;
using LabForWeb.MVC.Models;
using LabForWeb.MVC.Extensions;

namespace LabForWeb.MVC.Controllers;

public class CarrelloController : Controller
{
    private readonly ApplicationDbContext _dc;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;
    public CarrelloController(ApplicationDbContext dc, SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
    {
        _dc = dc;
        _userManager = userManager;
        _signInManager = signInManager;
    }
    public async Task<IActionResult> Index()
    {

        var user = await _userManager.GetUserAsync(User);
        //var userId = user?.Id; // a21a214d-7a39-4aa9-8c38-8804a0736db9

        // 2. cerco se esiste già un carrello NON chiuso dell'utente loggato
        // Include carica in autonomia tutti i carrelli di Dettagli in JOIN con carrello
        var carrelloAttivo = await _dc.Carrelli.Include(c => c.Dettaglio).ThenInclude(c =>c.Prodottto).SingleOrDefaultAsync(c => c.Utente == user && !c.DataChiusura.HasValue); // c => c.Utente!.Id == userId && !c.DataChiusura.HasValue


        List<CarrelloDettaglioModel> model = [];
        // 3. Se non c'é carrello vai avanti 
        if(carrelloAttivo != null)
        {
            model = carrelloAttivo.Dettaglio.Select(s => s.ToCarrelloDettaglioModel()).ToList();
        }


        return View(model);
    }

    [HttpPost]
    public async Task<ActionResult> Add(int prodottoId)
    {

        // Scrittura DB
        // 1. Recupero l'utente loggato
        var user =  await _userManager.GetUserAsync(User);
        //var userId = user?.Id; // a21a214d-7a39-4aa9-8c38-8804a0736db9

        // 2. cerco se esiste già un carrello NON chiuso dell'utente loggato
        // Include carica in autonomia tutti i carrelli di Dettagli in JOIN con carrello
        var carrelloAttivo = await _dc.Carrelli.Include(c=>c.Dettaglio).SingleOrDefaultAsync(c => c.Utente == user && !c.DataChiusura.HasValue); // c => c.Utente!.Id == userId && !c.DataChiusura.HasValue


        // 3. Se non o trovo ne creo uno nuovo
        if (carrelloAttivo == null)
        {
            carrelloAttivo = new Carrello(); // 
            carrelloAttivo.Utente = user;
            carrelloAttivo.DataCreazione = DateTime.Now;
            _dc.Carrelli.Add(carrelloAttivo); // Carica sul DB
        }

        // 4. Recupero il prodotto che voglio inserire
        var prodotto = await _dc.Prodotti.SingleAsync(p=> p.Id == prodottoId);

        // 5. Cerco se esiste già tra i Dettaglidel Carrello il prodotto che voglio inserire
        var dettaglio = carrelloAttivo.Dettaglio.SingleOrDefault(cd => cd.Prodottto == prodotto);

        // Se non esiste lo creo
        if(dettaglio == null)
        {
            dettaglio = new Carrello_Dettaglio { Prodottto = prodotto, Quantita = 1};
            carrelloAttivo.Dettaglio.Add(dettaglio);
        }

        // Se esiste aumento di uno la quantità
        else 
        {
            dettaglio.Quantita++;
         }


        try
        {
            _dc.SaveChanges();
        }
        catch (Exception ex)
        {
            // throw;
        }

        return RedirectToAction("Index", "Home");
    }
}

LabForWeb.MVC/Controllers/ProdottiController.cs
using LabForWeb.MVC.Data;
using LabForWeb.MVC.Extensions;
using LabForWeb.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.IO;
using System.Net;


namespace LabForWeb.MVC.Controllers;

public class ProdottiController : Controller
{

    private readonly ApplicationDbContext _context;
    public ProdottiController(ApplicationDbContext context)
    {
        _context= context;
    }
    public IActionResult Index()
    {
        // Dictionary che mappa CodiceFiscale => Nome Utente
        //var users = new Dictionary<string, string>();
        //users.Add("XYZ", "Matteo");
        //users.Add("BLL", "Bullo");

        //var matteo = users["XYZ"];

        //users["XYZ"] = "Franco";


        ViewData["Messaggio"] = "Ciao sono io!";

        //// POCO class
        //List<ProdottoModel> prodotti = [
        //    new ProdottoModel{
        //        Id = 1,
        //        Nome = "Ciabatte col pelo"
        //    },
        //    new ProdottoModel{
        //        Id = 2,
        //        Nome = "Bicicletta"
        //    }
        //];

        var prodotti= _context.Prodotti
            .OrderByDescending(x => x.Id)
            .Select(p => p.ToProdottoModle()).ToList();

        return View(prodotti);
    }

    public async Task<IActionResult> GetFakeData()
    {

        if (_context.Prodotti.Any()) return Ok(new {message = "Tutto già riempito"});

        var client = new HttpClient();

        var responseCategories = await client.GetFromJsonAsync<IEnumerable<DummyCategory>>("https://dummyjson.com/products/categories");

        var responseProducts = await client.GetFromJsonAsync<DammyJsonProductsResponse>("https://dummyjson.com/products");

        foreach (var c in responseCategories)
        {
            _context.Categorie.Add(new Data.Models.Categoria
            {
                Nome = c.Name,
                Slug = c.Slug
            });
        }

        await _context.SaveChangesAsync();

        foreach (var p in responseProducts.Products)
        {
            var prodotto = new Data.Models.Prodotto
            {
                Attivo = true,
                Descrizione = p.Description,
                DescrizioneBreve = p.Description,
                Giacenza = (short)p.Stock,
                ImageUrl = p.Thumbnail,
                Nome = p.Title,
                Prezzo = (decimal)p.Price,
                Visibile = true,
            };

            // Cerco la categoria che ha come Slug p.Category
            var cat = _context.Categorie.Single(c => c.Slug == p.Category);
            prodotto.Categorie.Add(cat);

            _context.Prodotti.Add(prodotto);
        }

        try
        {
           await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }


        Console.WriteLine(responseProducts);



        // return View(await _context.Prodotti.Select(s=>s.ToProdottoModle()).ToListAsync());
        return Ok(await _context.Prodotti.Select(s => s.ToProdottoModle()).ToListAsync());

    }

    [HttpGet]
    public async Task<IActionResult> Create()
    {
        var categorie = await _context.Categorie.Select(c => c.ToCategoriaModel()).ToListAsync();
        ViewData["Categorie"] = new SelectList(categorie, "Id", "Nome").ToList(); // guarda struttura Categoria Model 
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(ProdottoDTO prodotto)
    {

        if (ModelState.IsValid)
        {
            // Salva su DB

            try
            {

                var nuovoProdotto = new Data.Models.Prodotto
                {
                    Nome = prodotto.Nome,
                    Descrizione = prodotto.Descrizione,
                    DescrizioneBreve = prodotto.DescrizioneBreve,
                    Giacenza = prodotto.Giacenza,
                    Prezzo = prodotto.Prezzo,
                    Attivo = prodotto.Attivo,
                    Visibile = prodotto.Visibile,
                };

                // salvo il file su disco
                if (prodotto.Immagine != null && prodotto.Immagine.Length > 0) 
                    {
                    var uploadDir = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot","uploads");
                    Directory.CreateDirectory(uploadDir);

                    var fileName = Path.GetFileName(prodotto.Immagine.FileName); // ciabatte_con_il_pelo.jpg
                    var filePath = Path.Combine(uploadDir, fileName); // E:\LABFORWEB\Labforweb_CEMV\Blazor\Blazor_C\L003 - 2025.07.28\LabForWeb.EC\LabForWeb.MVC\wwwroot\uploads\ciabatte_con_il_pelo.jpg
                    
                    // Variante 1
                    using var stream = new FileStream(filePath, FileMode.Create);
                    await prodotto.Immagine.CopyToAsync(stream);

                    // Variante 2
                    // System.IO.File.WriteAllBytesAsync(filePath, prodotto.Immagine.);


                    nuovoProdotto.ImageUrl = $"/uploads/{fileName}"; // Path.Combine("/uploads", fileName);
                }


                var cat = await _context.Categorie.SingleAsync(c => c.Id == prodotto.CategoriaID);
                nuovoProdotto.Categorie.Add(cat);

                _context.Prodotti.Add(nuovoProdotto);

                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View(prodotto);
            }

            // return RedirectToAction("Index");
        }
        else
        {
            return View(prodotto);
        }
    }

    [HttpGet]
    public async Task<IActionResult> Delete(int id)
    {
        var prodotto = await _context.Prodotti.FindAsync(id);
        if (prodotto == null) return NotFound();
        return View(prodotto.ToProdottoModle()); // Devo farlo
    }

    [HttpPost, ActionName("Delete")]
    public async Task<IActionResult> DeletedConfirmed(int id)
    {
        var prodotto = await _context.Prodotti.FindAsync(id);
        if (prodotto == null) return NotFound();
        try
        {
            if (!string.IsNullOrEmpty(prodotto.ImageUrl) && prodotto.ImageUrl.StartsWith("/uploads"))
            {
                var filePath = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot", prodotto.ImageUrl[1..]) ;
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath); // Cancella se esiste
                }
            }
            _context.Prodotti.Remove(prodotto);

            await _context.SaveChangesAsync();
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }

        return RedirectToAction("Index", "Home");
    }

}

LabForWeb.MVC/Views/Shared/_CartMini.cshtml
@model int
<a asp-controller="Carrello" asp-action="Index" class="btn btn-primary position-relative m-3">
    <i class="bi bi-cart"></i>
    @if (Model > 0)
    {
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
            @Model
            <span class="visually-hidden">unread messages</span>
        </span>
    }

</a>

LabForWeb.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LabForWeb.MVC</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LabForWeb.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LabForWeb.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prodotti" asp-action="Index">Prodotti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categorie" asp-action="Index">Categorie</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_CartMini" model="@ViewData["ProdottiTotaliCarrello"]" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - LabForWeb.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LabForWeb.MVC/Views/Shared/_ProdottiGalleryPartial.cshtml
@using LabForWeb.MVC.Data
@using LabForWeb.MVC.Models;
@using Microsoft.AspNetCore.Identity
@model LabForWeb.MVC.Models.ProdottiGalleryPartialModel
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<h3>@Model.Titolo</h3>
<div class="row row-cols-1 row-cols-md-4 g-4">
    @foreach (var p in Model.Prodotti)
    {
        <div class="col">

            <div class="card">
                <img class="card-img-top" src="@p.ImageUrl" alt="@p.Nome"/>
                <div class="card-body">
                    <h5 class="card-title">@p.Nome</h5>
                    <p class="card-text">@p.DescrizioneBreve</p>
                    <div class="d-flex gap-3">
                        <a class="btn btn-danger" asp-controller="Prodotti" asp-action="Delete" asp-route-id="@p.Id">Elimina</a>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <form asp-action="Add" asp-controller="Carrello" method="post">
                                <input type="hidden" name="prodottoId" value="@p.Id" />
                                <button type="submit" class="btn btn-primary"> Aggiungi a carrello</button>
                            </form>
                        }         
                    </div>                    
                </div>
                
            </div>

        </div>
    }
 </div>